# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RisCli < Formula
  desc "CLI für das Rechtsinformationssystem des Bundes (RIS)"
  homepage "https://github.com/philrox/ris-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philrox/ris-cli/releases/download/v0.1.0/ris-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "60805e66d5e1b7366ee22d39a6a35c71a688ebc4c9dfa98c0481810c806f75bd"

      def install
        bin.install "ris"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philrox/ris-cli/releases/download/v0.1.0/ris-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "1807b4c76280e1532988a325d69b9cc87a770c0067b64478988b9dfed7741cec"

      def install
        bin.install "ris"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philrox/ris-cli/releases/download/v0.1.0/ris-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "5ca21c1748f1af1b2b6009011c56d31cc23813e41b54f583808857ce70b2982f"
      def install
        bin.install "ris"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philrox/ris-cli/releases/download/v0.1.0/ris-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "26fcab6f281ac7b0d813dd187ba116adde300df260603af44da8129cc9d702cf"
      def install
        bin.install "ris"
      end
    end
  end

  test do
    system "#{bin}/ris", "version"
  end
end
