# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ris < Formula
  desc "CLI für das Rechtsinformationssystem des Bundes (RIS)"
  homepage "https://github.com/philrox/ris-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philrox/ris-cli/releases/download/v0.1.1/ris-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "bb975d073a34a121b6ca7e226cc87a6857a855fe82a01708d8c98e684e7cb9ba"

      def install
        bin.install "ris"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philrox/ris-cli/releases/download/v0.1.1/ris-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "04c342fa78e2fb5ede24bf65a8a1031b6633653b00ada8ea9a344f4e6dbb822d"

      def install
        bin.install "ris"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philrox/ris-cli/releases/download/v0.1.1/ris-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "88401f091210577aa5a1bed99f351b920c38decfabf3c474e9d6c4c22b295db6"
      def install
        bin.install "ris"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philrox/ris-cli/releases/download/v0.1.1/ris-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "8707ac79b857366bb6cf7a6baba61712983914f64d0f241fb2210fe2e15fdd8b"
      def install
        bin.install "ris"
      end
    end
  end

  test do
    system "#{bin}/ris", "version"
  end
end
