# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Risgo < Formula
  desc "CLI für das Rechtsinformationssystem des Bundes (RIS)"
  homepage "https://github.com/philrox/risgo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philrox/risgo/releases/download/v0.1.0/risgo_0.1.0_darwin_amd64.tar.gz"
      sha256 "98042ecb1ce60352d08941f88f4dc75e0406dda669f52107d309040fca8fc1af"

      def install
        bin.install "risgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philrox/risgo/releases/download/v0.1.0/risgo_0.1.0_darwin_arm64.tar.gz"
      sha256 "b097e73fbb66164309893409557ec7da23a129b3c6f98a12e23d05c5d970e400"

      def install
        bin.install "risgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philrox/risgo/releases/download/v0.1.0/risgo_0.1.0_linux_amd64.tar.gz"
      sha256 "cf8f5d836f39ebe2f006b5f0692322e57ebb220454c283832d5a9e32b1bb2616"
      def install
        bin.install "risgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philrox/risgo/releases/download/v0.1.0/risgo_0.1.0_linux_arm64.tar.gz"
      sha256 "d7f3e2ee64020e37f30eae5541b9f5bd2bf566ead80e3be0c0e0ea9ff50a10aa"
      def install
        bin.install "risgo"
      end
    end
  end

  test do
    system "#{bin}/risgo", "version"
  end
end
